In [1]:
import json

with open('resume_data.json', 'r') as json_file:
    dataset = json.load(json_file)

In [2]:
import pandas as pd
df = pd.read_json('resume_data.json')

In [3]:
df.head()

,content,annotation,extras
0,Abhishek Jha\nApplication Development Associat...,"[{'label': ['Skills'], 'points': [{'start': 12...",NaN
1,Afreen Jamadar\nActive member of IIIT Committe...,"[{'label': ['Email Address'], 'points': [{'sta...",NaN
2,"Akhil Yadav Polemaina\nHyderabad, Telangana - ...","[{'label': ['Skills'], 'points': [{'start': 37...",NaN
3,Alok Khandai\nOperational Analyst (SQL DBA) En...,"[{'label': ['Skills'], 'points': [{'start': 80...",NaN
4,Ananya Chavan\nlecturer - oracle tutorials\n\n...,"[{'label': ['Degree'], 'points': [{'start': 20...",NaN

In [4]:
df['annotation'][0][0]

{'label': ['Skills'],
 'points': [{'start': 1295,
   'end': 1621,
   'text': '\n• Programming language: C, C++, Java\n• Oracle PeopleSoft\n• Internet Of Things\n• Machine Learning\n• Database Management System\n• Computer Networks\n• Operating System worked on: Linux, Windows, Mac\n\nNon - Technical Skills\n\n• Honest and Hard-Working\n• Tolerant and Flexible to Different Situations\n• Polite and Calm\n• Team-Player'}]}

In [5]:
df['extras'].isnull().sum()

220

In [6]:
len(df)

220

In [7]:
df.drop(['extras'],axis='columns',inplace=True)

In [8]:
df.head()

,content,annotation
0,Abhishek Jha\nApplication Development Associat...,"[{'label': ['Skills'], 'points': [{'start': 12..."
1,Afreen Jamadar\nActive member of IIIT Committe...,"[{'label': ['Email Address'], 'points': [{'sta..."
2,"Akhil Yadav Polemaina\nHyderabad, Telangana - ...","[{'label': ['Skills'], 'points': [{'start': 37..."
3,Alok Khandai\nOperational Analyst (SQL DBA) En...,"[{'label': ['Skills'], 'points': [{'start': 80..."
4,Ananya Chavan\nlecturer - oracle tutorials\n\n...,"[{'label': ['Degree'], 'points': [{'start': 20..."

In [9]:
# import string
# import re
# def clean_text(text):
#     # Convert to lowercase
#     text = text.lower()
#     # Remove punctuation marks
#     text = text.translate(str.maketrans("", "", string.punctuation))
#     # Remove extra whitespaces
#     text = re.sub(r'\s+', ' ', text).strip()
#     return text

# # Example usage:
# df['content'] = df['content'].apply(clean_text)
# df.head()

In [10]:
df['annotation'][0]

[{'label': ['Skills'],
  'points': [{'start': 1295,
    'end': 1621,
    'text': '\n• Programming language: C, C++, Java\n• Oracle PeopleSoft\n• Internet Of Things\n• Machine Learning\n• Database Management System\n• Computer Networks\n• Operating System worked on: Linux, Windows, Mac\n\nNon - Technical Skills\n\n• Honest and Hard-Working\n• Tolerant and Flexible to Different Situations\n• Polite and Calm\n• Team-Player'}]},
 {'label': ['Skills'],
  'points': [{'start': 993,
    'end': 1153,
    'text': 'C (Less than 1 year), Database (Less than 1 year), Database Management (Less than 1 year),\nDatabase Management System (Less than 1 year), Java (Less than 1 year)'}]},
 {'label': ['College Name'],
  'points': [{'start': 939, 'end': 956, 'text': 'Kendriya Vidyalaya'}]},
 {'label': ['College Name'],
  'points': [{'start': 883, 'end': 904, 'text': 'Woodbine modern school'}]},
 {'label': ['Graduation Year'],
  'points': [{'start': 856, 'end': 860, 'text': '2017\n'}]},
 {'label': ['College Name'],
  'points': [{'start': 771,
    'end': 813,
    'text': 'B.v.b college of engineering and technology'}]},
 {'label': ['Designation'],
  'points': [{'start': 727,
    'end': 769,
    'text': 'B.E in Information science and engineering\n'}]},
 {'label': ['Companies worked at'],
  'points': [{'start': 407, 'end': 415, 'text': 'Accenture'}]},
 {'label': ['Designation'],
  'points': [{'start': 372,
    'end': 404,
    'text': 'Application Development Associate'}]},
 {'label': ['Email Address'],
  'points': [{'start': 95,
    'end': 145,
    'text': 'Indeed: indeed.com/r/Abhishek-Jha/10e7a8cb732bc43a\n'}]},
 {'label': ['Location'],
  'points': [{'start': 60, 'end': 68, 'text': 'Bengaluru'}]},
 {'label': ['Companies worked at'],
  'points': [{'start': 49, 'end': 57, 'text': 'Accenture'}]},
 {'label': ['Designation'],
  'points': [{'start': 13,
    'end': 45,
    'text': 'Application Development Associate'}]},
 {'label': ['Name'],
  'points': [{'start': 0, 'end': 11, 'text': 'Abhishek Jha'}]}]

In [22]:
def convert_to_iob(labels):
    iob_labels = []
    for label in labels:
        if label['label']:
            entity_label = label['label'][0]
            iob_labels.append([(ent['start'], ent['end']+1, f'B-{entity_label}') for ent in label['points']])
    return iob_labels

In [23]:
df['Y_iob'] = df['annotation'].apply(convert_to_iob)

In [24]:
df.head()

,content,annotation,Y_iob
0,abhishek jha\napplication development associat...,"[{'label': ['Skills'], 'points': [{'start': 12...","[[(1295, 1622, B-Skills)], [(993, 1154, B-Skil..."
1,afreen jamadar\nactive member of iiit committe...,"[{'label': ['Email Address'], 'points': [{'sta...","[[(1155, 1199, B-Email Address)], [(743, 1141,..."
2,"akhil yadav polemaina\nhyderabad, telangana - ...","[{'label': ['Skills'], 'points': [{'start': 37...","[[(3749, 3757, B-Skills)], [(3709, 3718, B-Ski..."
3,alok khandai\noperational analyst (sql dba) en...,"[{'label': ['Skills'], 'points': [{'start': 80...","[[(8098, 8384, B-Skills)], [(8008, 8050, B-Ski..."
4,ananya chavan\nlecturer - oracle tutorials\n\n...,"[{'label': ['Degree'], 'points': [{'start': 20...","[[(2010, 2013, B-Degree)], [(973, 1703, B-Skil..."

In [25]:
df['Y_iob'][0]

[[(1295, 1622, 'B-Skills')],
 [(993, 1154, 'B-Skills')],
 [(939, 957, 'B-College Name')],
 [(883, 905, 'B-College Name')],
 [(856, 861, 'B-Graduation Year')],
 [(771, 814, 'B-College Name')],
 [(727, 770, 'B-Designation')],
 [(407, 416, 'B-Companies worked at')],
 [(372, 405, 'B-Designation')],
 [(95, 146, 'B-Email Address')],
 [(60, 69, 'B-Location')],
 [(49, 58, 'B-Companies worked at')],
 [(13, 46, 'B-Designation')],
 [(0, 12, 'B-Name')]]

In [26]:
df['content'] = df['content'].apply(lambda x : x.lower())

In [27]:
df.head()

,content,annotation,Y_iob
0,abhishek jha\napplication development associat...,"[{'label': ['Skills'], 'points': [{'start': 12...","[[(1295, 1622, B-Skills)], [(993, 1154, B-Skil..."
1,afreen jamadar\nactive member of iiit committe...,"[{'label': ['Email Address'], 'points': [{'sta...","[[(1155, 1199, B-Email Address)], [(743, 1141,..."
2,"akhil yadav polemaina\nhyderabad, telangana - ...","[{'label': ['Skills'], 'points': [{'start': 37...","[[(3749, 3757, B-Skills)], [(3709, 3718, B-Ski..."
3,alok khandai\noperational analyst (sql dba) en...,"[{'label': ['Skills'], 'points': [{'start': 80...","[[(8098, 8384, B-Skills)], [(8008, 8050, B-Ski..."
4,ananya chavan\nlecturer - oracle tutorials\n\n...,"[{'label': ['Degree'], 'points': [{'start': 20...","[[(2010, 2013, B-Degree)], [(973, 1703, B-Skil..."

In [29]:
from keras.preprocessing.text import Tokenizer
y_tokenizer = Tokenizer()

flattened_labels = [label[0][2] for sublist in df['Y_iob'] for label in sublist]

y_tokenizer.fit_on_texts(flattened_labels)

In [51]:
y_tokenizer.index_word

{1: 'b',
 2: 'companies',
 3: 'worked',
 4: 'at',
 5: 'name',
 6: 'designation',
 7: 'skills',
 8: 'location',
 9: 'college',
 10: 'degree',
 11: 'graduation',
 12: 'year',
 13: 'email',
 14: 'address',
 15: 'years',
 16: 'of',
 17: 'experience',
 18: 'unknown'}

In [31]:
flattened_labels

['B-Skills',
 'B-Skills',
 'B-College Name',
 'B-College Name',
 'B-Graduation Year',
 'B-College Name',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Email Address',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Email Address',
 'B-Location',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-College Name',
 'B-Degree',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-College Name',
 'B-Location',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Degree',
 'B-Skills',
 'B-Location',
 'B-College Name',
 'B-Degree',
 'B-College Name',
 'B-Degree',
 'B-Designation',
 'B-Designation',
 'B-Designation',
 'B-Location',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Graduation Year',
 'B-Location',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Email Address',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-Location',
 'B-Companies worked at',
 'B-Graduation Year',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-Email Address',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Years of Experience',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Location',
 'B-College Name',
 'B-Degree',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Years of Experience',
 'B-Location',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Degree',
 'B-College Name',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Skills',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Designation',
 'B-Designation',
 'B-Email Address',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Email Address',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-College Name',
 'B-College Name',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Companies worked at',
 'B-Graduation Year',
 'B-Companies worked at',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Location',
 'B-College Name',
 'B-Degree',
 'B-Location',
 'B-College Name',
 'B-Location',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Email Address',
 'B-Skills',
 'B-College Name',
 'B-Graduation Year',
 'B-Degree',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Name',
 'B-Skills',
 'B-College Name',
 'B-Degree',
 'B-College Name',
 'B-Degree',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Companies worked at',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Graduation Year',
 'B-Degree',
 'B-Degree',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Graduation Year',
 'B-Location',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-Location',
 'B-Location',
 'B-Graduation Year',
 'B-Location',
 'B-Location',
 'B-Designation',
 'B-Email Address',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Designation',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Graduation Year',
 'B-Location',
 'B-Location',
 'B-College Name',
 'B-Graduation Year',
 'B-Location',
 'B-Location',
 'B-College Name',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-College Name',
 'B-Degree',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Location',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Location',
 'B-Location',
 'B-Name',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Skills',
 'B-Companies worked at',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Email Address',
 'B-Location',
 'B-Designation',
 'B-Name',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Skills',
 'B-College Name',
 'B-Degree',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Location',
 'B-Location',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Designation',
 'B-Years of Experience',
 'B-Location',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Email Address',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Location',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-College Name',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Graduation Year',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-College Name',
 'B-Graduation Year',
 'B-Location',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Location',
 'B-Designation',
 'B-Name',
 'B-Graduation Year',
 'B-Degree',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Skills',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-Skills',
 'B-Companies worked at',
 'B-Email Address',
 'B-Location',
 'B-Name',
 'B-Graduation Year',
 'B-College Name',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Skills',
 'B-Companies worked at',
 'B-Years of Experience',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-College Name',
 'B-Location',
 'B-College Name',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Graduation Year',
 'B-Companies worked at',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-Skills',
 'B-Location',
 'B-Location',
 'B-Designation',
 'B-Location',
 'B-Skills',
 'B-Companies worked at',
 'B-Designation',
 'B-Skills',
 'B-Degree',
 'B-Email Address',
 'B-Location',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Companies worked at',
 'B-Skills',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-College Name',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Degree',
 'B-Companies worked at',
 'B-College Name',
 'B-Email Address',
 'B-Graduation Year',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-College Name',
 'B-College Name',
 'B-College Name',
 'B-Degree',
 'B-College Name',
 'B-Email Address',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-College Name',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Name',
 'B-Skills',
 'B-College Name',
 'B-College Name',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Location',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Designation',
 'B-Name',
 'B-Graduation Year',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Name',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Graduation Year',
 'B-Location',
 'B-Degree',
 'B-Degree',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Email Address',
 'B-Graduation Year',
 'B-Companies worked at',
 'B-Designation',
 'B-Skills',
 'B-Graduation Year',
 'B-Location',
 'B-Graduation Year',
 'B-Location',
 'B-Companies worked at',
 'B-Email Address',
 'B-Location',
 'B-Name',
 'B-Skills',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Designation',
 'B-Location',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-Skills',
 'B-College Name',
 'B-Graduation Year',
 'B-College Name',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Designation',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-Designation',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-Companies worked at',
 'B-Designation',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Email Address',
 'B-Location',
 'B-Name',
 'B-Skills',
 'B-College Name',
 'B-Degree',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Designation',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Years of Experience',
 'B-Email Address',
 'B-Location',
 'B-Name',
 'B-Skills',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Skills',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Email Address',
 'B-Companies worked at',
 'B-Graduation Year',
 'B-College Name',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Graduation Year',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Years of Experience',
 'B-Email Address',
 'B-Location',
 'B-Name',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Designation',
 'B-Location',
 'B-Years of Experience',
 'B-Email Address',
 'B-Location',
 'B-Designation',
 'B-Name',
 'B-Companies worked at',
 'B-Skills',
 'B-College Name',
 'B-Graduation Year',
 'B-College Name',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Graduation Year',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Graduation Year',
 'B-Skills',
 'B-College Name',
 'B-College Name',
 'B-Graduation Year',
 'B-Location',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Location',
 'B-Designation',
 'B-Name',
 'B-Location',
 'B-Skills',
 'B-College Name',
 'B-Email Address',
 'B-Degree',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Location',
 'B-Skills',
 'B-Graduation Year',
 'B-Location',
 'B-Location',
 'B-Degree',
 'B-Graduation Year',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Graduation Year',
 'B-Companies worked at',
 'B-Designation',
 'B-Location',
 'B-Location',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Name',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-Skills',
 'B-Skills',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-College Name',
 'B-Degree',
 'B-Graduation Year',
 'B-Degree',
 'B-Email Address',
 'B-Designation',
 'B-Designation',
 'B-Designation',
 'B-Email Address',
 'B-Companies worked at',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Graduation Year',
 'B-Location',
 'B-College Name',
 'B-College Name',
 'B-Degree',
 'B-Companies worked at',
 'B-Designation',
 'B-Graduation Year',
 'B-Graduation Year',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Graduation Year',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Companies worked at',
 'B-Location',
 'B-Companies worked at',
 'B-Designation',
 'B-Email Address',
 'B-Location',
 'B-Degree',
 'B-Years of Experience',
 'B-Designation',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-College Name',
 'B-Degree',
 'B-College Name',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Degree',
 'B-Email Address',
 'B-Companies worked at',
 'B-Companies worked at',
 'B-Designation',
 'B-Degree',
 'B-Degree',
 'B-Email Address',
 'B-Location',
 'B-Name',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Graduation Year',
 'B-College Name',
 'B-Degree',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Designation',
 'B-Designation',
 'B-Skills',
 'B-Email Address',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Designation',
 'B-Designation',
 'B-Designation',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 'B-Skills',
 ...]

In [69]:
classes = list(set(flattened_labels))
num_of_classes = len(classes)
num_of_classes

11

In [39]:
y_tokenized = [y_tokenizer.texts_to_sequences([label[0][2]])[0] for sublist in df['Y_iob'] for label in sublist]

In [41]:
y_tokenized

[[1, 7],
 [1, 7],
 [1, 9, 5],
 [1, 9, 5],
 [1, 11, 12],
 [1, 9, 5],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 13, 14],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 13, 14],
 [1, 8],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 9, 5],
 [1, 10],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 9, 5],
 [1, 8],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 10],
 [1, 7],
 [1, 8],
 [1, 9, 5],
 [1, 10],
 [1, 9, 5],
 [1, 10],
 [1, 6],
 [1, 6],
 [1, 6],
 [1, 8],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 11, 12],
 [1, 8],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 13, 14],
 [1, 11, 12],
 [1, 11, 12],
 [1, 8],
 [1, 2, 3, 4],
 [1, 11, 12],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 13, 14],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 15, 16, 17],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 8],
 [1, 9, 5],
 [1, 10],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 15, 16, 17],
 [1, 8],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 10],
 [1, 9, 5],
 [1, 11, 12],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 7],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 6],
 [1, 6],
 [1, 13, 14],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 13, 14],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 9, 5],
 [1, 9, 5],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 2, 3, 4],
 [1, 11, 12],
 [1, 2, 3, 4],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 8],
 [1, 9, 5],
 [1, 10],
 [1, 8],
 [1, 9, 5],
 [1, 8],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 13, 14],
 [1, 7],
 [1, 9, 5],
 [1, 11, 12],
 [1, 10],
 [1, 11, 12],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 5],
 [1, 7],
 [1, 9, 5],
 [1, 10],
 [1, 9, 5],
 [1, 10],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 2, 3, 4],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 11, 12],
 [1, 10],
 [1, 10],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 11, 12],
 [1, 8],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 8],
 [1, 8],
 [1, 11, 12],
 [1, 8],
 [1, 8],
 [1, 6],
 [1, 13, 14],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 6],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 11, 12],
 [1, 8],
 [1, 8],
 [1, 9, 5],
 [1, 11, 12],
 [1, 8],
 [1, 8],
 [1, 9, 5],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 9, 5],
 [1, 10],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 8],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 8],
 [1, 8],
 [1, 5],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 7],
 [1, 2, 3, 4],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 13, 14],
 [1, 8],
 [1, 6],
 [1, 5],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 7],
 [1, 9, 5],
 [1, 10],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 8],
 [1, 8],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 6],
 [1, 15, 16, 17],
 [1, 8],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 13, 14],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 8],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 9, 5],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 11, 12],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 9, 5],
 [1, 11, 12],
 [1, 8],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 8],
 [1, 6],
 [1, 5],
 [1, 11, 12],
 [1, 10],
 [1, 11, 12],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 7],
 [1, 11, 12],
 [1, 11, 12],
 [1, 7],
 [1, 2, 3, 4],
 [1, 13, 14],
 [1, 8],
 [1, 5],
 [1, 11, 12],
 [1, 9, 5],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 7],
 [1, 2, 3, 4],
 [1, 15, 16, 17],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 9, 5],
 [1, 8],
 [1, 9, 5],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 11, 12],
 [1, 2, 3, 4],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 7],
 [1, 8],
 [1, 8],
 [1, 6],
 [1, 8],
 [1, 7],
 [1, 2, 3, 4],
 [1, 6],
 [1, 7],
 [1, 10],
 [1, 13, 14],
 [1, 8],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 2, 3, 4],
 [1, 7],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 9, 5],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 10],
 [1, 2, 3, 4],
 [1, 9, 5],
 [1, 13, 14],
 [1, 11, 12],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 9, 5],
 [1, 9, 5],
 [1, 9, 5],
 [1, 10],
 [1, 9, 5],
 [1, 13, 14],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 9, 5],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 5],
 [1, 7],
 [1, 9, 5],
 [1, 9, 5],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 8],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 6],
 [1, 5],
 [1, 11, 12],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 5],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 11, 12],
 [1, 8],
 [1, 10],
 [1, 10],
 [1, 11, 12],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 13, 14],
 [1, 11, 12],
 [1, 2, 3, 4],
 [1, 6],
 [1, 7],
 [1, 11, 12],
 [1, 8],
 [1, 11, 12],
 [1, 8],
 [1, 2, 3, 4],
 [1, 13, 14],
 [1, 8],
 [1, 5],
 [1, 7],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 6],
 [1, 8],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 11, 12],
 [1, 11, 12],
 [1, 7],
 [1, 9, 5],
 [1, 11, 12],
 [1, 9, 5],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 6],
 [1, 11, 12],
 [1, 11, 12],
 [1, 6],
 [1, 11, 12],
 [1, 11, 12],
 [1, 11, 12],
 [1, 11, 12],
 [1, 2, 3, 4],
 [1, 6],
 [1, 11, 12],
 [1, 11, 12],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 13, 14],
 [1, 8],
 [1, 5],
 [1, 7],
 [1, 9, 5],
 [1, 10],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 6],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 15, 16, 17],
 [1, 13, 14],
 [1, 8],
 [1, 5],
 [1, 7],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 7],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 13, 14],
 [1, 2, 3, 4],
 [1, 11, 12],
 [1, 9, 5],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 11, 12],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 15, 16, 17],
 [1, 13, 14],
 [1, 8],
 [1, 5],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 6],
 [1, 8],
 [1, 15, 16, 17],
 [1, 13, 14],
 [1, 8],
 [1, 6],
 [1, 5],
 [1, 2, 3, 4],
 [1, 7],
 [1, 9, 5],
 [1, 11, 12],
 [1, 9, 5],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 11, 12],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 11, 12],
 [1, 7],
 [1, 9, 5],
 [1, 9, 5],
 [1, 11, 12],
 [1, 8],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 8],
 [1, 6],
 [1, 5],
 [1, 8],
 [1, 7],
 [1, 9, 5],
 [1, 13, 14],
 [1, 10],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 8],
 [1, 7],
 [1, 11, 12],
 [1, 8],
 [1, 8],
 [1, 10],
 [1, 11, 12],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 11, 12],
 [1, 2, 3, 4],
 [1, 6],
 [1, 8],
 [1, 8],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 5],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 7],
 [1, 7],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 9, 5],
 [1, 10],
 [1, 11, 12],
 [1, 10],
 [1, 13, 14],
 [1, 6],
 [1, 6],
 [1, 6],
 [1, 13, 14],
 [1, 2, 3, 4],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 11, 12],
 [1, 8],
 [1, 9, 5],
 [1, 9, 5],
 [1, 10],
 [1, 2, 3, 4],
 [1, 6],
 [1, 11, 12],
 [1, 11, 12],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 11, 12],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 2, 3, 4],
 [1, 8],
 [1, 2, 3, 4],
 [1, 6],
 [1, 13, 14],
 [1, 8],
 [1, 10],
 [1, 15, 16, 17],
 [1, 6],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 9, 5],
 [1, 10],
 [1, 9, 5],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 10],
 [1, 13, 14],
 [1, 2, 3, 4],
 [1, 2, 3, 4],
 [1, 6],
 [1, 10],
 [1, 10],
 [1, 13, 14],
 [1, 8],
 [1, 5],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 11, 12],
 [1, 9, 5],
 [1, 10],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 6],
 [1, 6],
 [1, 7],
 [1, 13, 14],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 6],
 [1, 6],
 [1, 6],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 [1, 7],
 ...]

In [58]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
y_padded = pad_sequences(y_tokenized, padding='post', value=0 , maxlen=3015)

In [59]:
y_padded

array([[1, 7, 0, ..., 0, 0, 0],
       [1, 7, 0, ..., 0, 0, 0],
       [1, 9, 5, ..., 0, 0, 0],
       ...,
       [1, 2, 3, ..., 0, 0, 0],
       [1, 6, 0, ..., 0, 0, 0],
       [1, 5, 0, ..., 0, 0, 0]], dtype=int32)

In [60]:
max_len_y = max(len(x) for x in y_padded)
max_len_y

3015

In [46]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(df['content'])
X_tokenized = tokenizer.texts_to_sequences(df['content'])

In [50]:
tokenizer.index_word

{1: 'and',
 2: '•',
 3: 'the',
 4: 'to',
 5: 'in',
 6: 'of',
 7: 'for',
 8: 'on',
 9: 'with',
 10: 'a',
 11: 'indeed',
 12: 'management',
 13: 'com',
 14: 'download',
 15: 'as',
 16: 'experience',
 17: 'r',
 18: 'project',
 19: 'team',
 20: 'skills',
 21: '➢',
 22: 'testing',
 23: 'work',
 24: '1',
 25: 'data',
 26: 'microsoft',
 27: 'test',
 28: 'using',
 29: 'years',
 30: 'client',
 31: 'from',
 32: 'https',
 33: 'year',
 34: 'www',
 35: 'co',
 36: 'support',
 37: 'application',
 38: 'is',
 39: 'oracle',
 40: 'business',
 41: 'by',
 42: 'sql',
 43: 'top',
 44: 'system',
 45: 'technical',
 46: 'it',
 47: 'isid',
 48: 'rex',
 49: 'ikw',
 50: 'software',
 51: 'server',
 52: 'development',
 53: 'all',
 54: 'information',
 55: 'sap',
 56: 'than',
 57: 'tools',
 58: 'knowledge',
 59: 'me',
 60: '2',
 61: 'process',
 62: 'email',
 63: 'education',
 64: 'infosys',
 65: 'engineer',
 66: 'worked',
 67: 'less',
 68: 'new',
 69: 'customer',
 70: 'i',
 71: 'windows',
 72: 'karnataka',
 73: 'c',
 74: 'web',
 75: 'systems',
 76: 'working',
 77: 'issues',
 78: 'technology',
 79: '2016',
 80: 'applications',
 81: 'java',
 82: 'service',
 83: 'database',
 84: 'at',
 85: '●',
 86: 'like',
 87: 'services',
 88: 'an',
 89: '3',
 90: 'responsibilities',
 91: 'present',
 92: 'end',
 93: 'design',
 94: 'involved',
 95: 'that',
 96: 'amp',
 97: 'based',
 98: 'good',
 99: '2015',
 100: 'additional',
 101: 'india',
 102: 'report',
 103: 'automation',
 104: 'environment',
 105: 'which',
 106: 'tool',
 107: '❖',
 108: 'ms',
 109: 'quality',
 110: '2013',
 111: '2017',
 112: 'various',
 113: 'used',
 114: '4',
 115: 'analysis',
 116: 'this',
 117: 'university',
 118: '2012',
 119: 'technologies',
 120: 'my',
 121: 'configuration',
 122: '2014',
 123: 'developed',
 124: 'requirements',
 125: 'performance',
 126: 'manager',
 127: '5',
 128: 'user',
 129: 'have',
 130: 'training',
 131: 'june',
 132: 'communication',
 133: 'implementation',
 134: 'cisco',
 135: 'reports',
 136: 'limited',
 137: 'lead',
 138: 'functional',
 139: 'be',
 140: 'consultant',
 141: 'maharashtra',
 142: 'sales',
 143: 'b',
 144: 'office',
 145: 'engineering',
 146: '6',
 147: 'network',
 148: 'product',
 149: 'ltd',
 150: 'bengaluru',
 151: '7',
 152: 'projects',
 153: 'cloud',
 154: 'bangalore',
 155: 'net',
 156: 'up',
 157: 'responsible',
 158: 'order',
 159: 'college',
 160: 'production',
 161: 'azure',
 162: 'monitoring',
 163: 'role',
 164: 'creating',
 165: 'activities',
 166: 'security',
 167: 'developer',
 168: 'handling',
 169: '2010',
 170: 'computer',
 171: 'or',
 172: 'different',
 173: 'level',
 174: 'time',
 175: '2011',
 176: 'related',
 177: 'company',
 178: '2008',
 179: 'cases',
 180: 'reporting',
 181: 'senior',
 182: '◦',
 183: 'integration',
 184: 'troubleshooting',
 185: 'solution',
 186: 'july',
 187: '✓',
 188: 'linux',
 189: 'per',
 190: 'willing',
 191: 'other',
 192: 'operating',
 193: 'organization',
 194: 'through',
 195: 'may',
 196: 'solutions',
 197: 'was',
 198: 'relocate',
 199: 'can',
 200: 'tamil',
 201: 'build',
 202: 'school',
 203: 'high',
 204: 'operations',
 205: 'excel',
 206: 'requirement',
 207: 'etc',
 208: 'nadu',
 209: 'platform',
 210: 'code',
 211: 'description',
 212: 'planning',
 213: 'ability',
 214: 'roles',
 215: 'are',
 216: '10',
 217: 'professional',
 218: 'customers',
 219: 'deployment',
 220: 'pune',
 221: 'also',
 222: 'languages',
 223: 'providing',
 224: 'delivery',
 225: 'access',
 226: 'key',
 227: 'telangana',
 228: 'creation',
 229: 'provide',
 230: 'hyderabad',
 231: 'maintenance',
 232: 'analyst',
 233: 'january',
 234: 'e',
 235: 'multiple',
 236: 'problem',
 237: 'job',
 238: 'managing',
 239: 'december',
 240: 'daily',
 241: 'science',
 242: 'pradesh',
 243: 'change',
 244: 'will',
 245: 'framework',
 246: 'program',
 247: 'products',
 248: 'clients',
 249: 'release',
 250: 'understanding',
 251: 'september',
 252: 'administration',
 253: 'tracking',
 254: 'maintaining',
 255: 'bi',
 256: 'issue',
 257: 'august',
 258: 'servers',
 259: 'module',
 260: 'core',
 261: 'october',
 262: 'designing',
 263: 'well',
 264: 'tech',
 265: 'global',
 266: 'banking',
 267: 'programming',
 268: 'their',
 269: 'having',
 270: 'marketing',
 271: 'details',
 272: 'has',
 273: 'implemented',
 274: 's',
 275: 'processes',
 276: '2007',
 277: 'group',
 278: 'users',
 279: '2005',
 280: 'automated',
 281: '8',
 282: 'agile',
 283: 'april',
 284: 'strong',
 285: 'manage',
 286: 'february',
 287: 'jenkins',
 288: 'architecture',
 289: 'developing',
 290: 'march',
 291: 'html',
 292: 'domain',
 293: 'institute',
 294: 'document',
 295: 'excellent',
 296: 'basic',
 297: 'power',
 298: 'manual',
 299: 'teams',
 300: 'months',
 301: 'crm',
 302: 'associate',
 303: 'environments',
 304: 'qa',
 305: 'created',
 306: 'defect',
 307: 'control',
 308: 'any',
 309: 'basis',
 310: 'across',
 311: 'expertise',
 312: 'ensure',
 313: 'incident',
 314: 'plan',
 315: 'enterprise',
 316: '0',
 317: 'master',
 318: 'day',
 319: 'asp',
 320: 'november',
 321: 'over',
 322: 'pvt',
 323: 'python',
 324: 'scripts',
 325: 'internal',
 326: 'solving',
 327: 'center',
 328: 'chennai',
 329: 'language',
 330: 'use',
 331: 'review',
 332: 'selenium',
 333: 'members',
 334: 'implementing',
 335: 'resource',
 336: 'performed',
 337: 'studio',
 338: 'duration',
 339: 'jira',
 340: 'required',
 341: 'best',
 342: 'such',
 343: 'installation',
 344: 'sharepoint',
 345: 'account',
 346: 'hr',
 347: 'modules',
 348: 'skill',
 349: 'create',
 350: 'bachelor',
 351: 'part',
 352: 'size',
 353: 'migration',
 354: 'ui',
 355: 'continuous',
 356: 'executive',
 357: 'date',
 358: 'within',
 359: 'ibm',
 360: 'member',
 361: 'hp',
 362: 'including',
 363: 'board',
 364: 'unix',
 365: 'abap',
 366: 'status',
 367: 'them',
 368: 'configuring',
 369: '2018',
 370: 'api',
 371: '2009',
 372: 'scripting',
 373: 'tickets',
 374: 'develop',
 375: 'out',
 376: 'store',
 377: 'setup',
 378: 'where',
 379: 'word',
 380: 'documents',
 381: 'analytical',
 382: 'into',
 383: 'maintain',
 384: 'case',
 385: 'aws',
 386: 'perform',
 387: 'visual',
 388: 'git',
 389: 'financial',
 390: 'areas',
 391: 'monthly',
 392: 'changes',
 393: 'unit',
 394: 'mobile',
 395: 'set',
 396: 'meetings',
 397: 'more',
 398: 'procedures',
 399: 'backup',
 400: 'o',
 401: 'features',
 402: 'regression',
 403: 'provided',
 404: 'execution',
 405: 'point',
 406: 'exchange',
 407: 'infrastructure',
 408: 'both',
 409: 'leading',
 410: 'file',
 411: 'anywhere',
 412: 'linkedin',
 413: 'online',
 414: 'preparing',
 415: 'oriented',
 416: 'till',
 417: 'completed',
 418: 'when',
 419: 'we',
 420: 'http',
 421: 'state',
 422: 'javascript',
 423: 'hardware',
 424: 'one',
 425: 'interface',
 426: 'learning',
 427: 'active',
 428: 'setting',
 429: 'site',
 430: 'under',
 431: 'purchase',
 432: 'm',
 433: 'track',
 434: 'maven',
 435: 'delhi',
 436: 'model',
 437: 'maximo',
 438: 'defects',
 439: 'leadership',
 440: 'its',
 441: 'each',
 442: 'building',
 443: 'vendor',
 444: '2004',
 445: 'bank',
 446: 'complete',
 447: 'devops',
 448: 'growth',
 449: 'queries',
 450: 'incidents',
 451: '〓',
 452: 'eclipse',
 453: 'analytics',
 454: 'life',
 455: 'routing',
 456: 'help',
 457: 'effective',
 458: 'designed',
 459: 'xp',
 460: 'functionality',
 461: 'css',
 462: 'interpersonal',
 463: 'area',
 464: 'existing',
 465: 'cycle',
 466: 'employees',
 467: 'complex',
 468: 'db',
 469: 'resolving',
 470: 'networking',
 471: 'exposure',
 472: 'documentation',
 473: 'databases',
 474: 'resources',
 475: 'about',
 476: 'during',
 477: 'svn',
 478: 'risk',
 479: 'accounts',
 480: 'storage',
 481: 'given',
 482: 'uttar',
 483: 'mysql',
 484: 'critical',
 485: 'weekly',
 486: 'award',
 487: 'script',
 488: 'real',
 489: 'post',
 490: 'components',
 491: 'certified',
 492: 'objects',
 493: 'managed',
 494: 'performing',
 495: 'corporation',
 496: 'industry',
 497: '☑',
 498: 'employee',
 499: 'concepts',
 500: 'coordinating',
 501: 'multi',
 502: 'traffic',
 503: 'between',
 504: 'hands',
 505: 'inventory',
 506: 'front',
 507: 'corporate',
 508: 'personal',
 509: 'overall',
 510: '9',
 511: 'standard',
 512: 'ensuring',
 513: 'preparation',
 514: 'protocols',
 515: 'escalation',
 516: 'fusion',
 517: 'accenture',
 518: 'player',
 519: 'received',
 520: 'finance',
 521: 'amazon',
 522: 'load',
 523: 'calls',
 524: 'methodologies',
 525: 'handled',
 526: 'done',
 527: 'highly',
 528: 'writing',
 529: 'files',
 530: 'request',
 531: 'dashboards',
 532: 'admin',
 533: '♦',
 534: 'currently',
 535: 'v',
 536: 'xml',
 537: 'retail',
 538: 'major',
 539: 'electronics',
 540: 'pl',
 541: 'field',
 542: 'self',
 543: 'successfully',
 544: 'private',
 545: 'payment',
 546: 'strategies',
 547: 'g',
 548: 'plans',
 549: 'us',
 550: 'not',
 551: 'asset',
 552: 'source',
 553: 'shell',
 554: 'understand',
 555: 'p',
 556: 'processing',
 557: 'tasks',
 558: 'supporting',
 559: 'improvement',
 560: 'international',
 561: 'live',
 562: 'back',
 563: 'problems',
 564: 'am',
 565: 'partner',
 566: 'card',
 567: 'same',
 568: 'care',
 569: 'video',
 570: 'uat',
 571: 'content',
 572: 'google',
 573: 'along',
 574: 'version',
 575: 'needs',
 576: 'search',
 577: 'intelligence',
 578: 'total',
 579: 'custom',
 580: 'andhra',
 581: 'results',
 582: 'branch',
 583: 'effectively',
 584: 'cross',
 585: 'offshore',
 586: 'requests',
 587: 'while',
 588: 'record',
 589: 'name',
 590: 'website',
 591: 'number',
 592: 'view',
 593: 'links',
 594: 'resolve',
 595: 'coding',
 596: 'forms',
 597: 'feature',
 598: 'transactions',
 599: 'many',
 600: 'sd',
 601: 'estimation',
 602: 'west',
 603: 'provides',
 604: 'portal',
 605: 'jobs',
 606: 'current',
 607: 'app',
 608: 'call',
 609: 'mumbai',
 610: 'uk',
 611: 'implement',
 612: 'tested',
 613: 'secondary',
 614: 'cost',
 615: 'gathering',
 616: 'dev',
 617: 'cash',
 618: 'kerala',
 619: 'architect',
 620: 'strategy',
 621: 'kumar',
 622: 'taking',
 623: '…',
 624: '2003',
 625: 'identifying',
 626: 'public',
 627: 'resolution',
 628: 'title',
 629: 'integrated',
 630: 'd',
 631: 'coordinator',
 632: 'programs',
 633: 'people',
 634: 'releases',
 635: 'engineers',
 636: '2006',
 637: 'making',
 638: 'participated',
 639: 'deploying',
 640: 'logic',
 641: 'challenging',
 642: 'if',
 643: 'middleware',
 644: 'regarding',
 645: 'finacle',
 646: 'bengal',
 647: 'activity',
 648: 'monitor',
 649: '2000',
 650: 'includes',
 651: 'recovery',
 652: 'memory',
 653: 'devices',
 654: 'mentoring',
 655: 'been',
 656: 'towards',
 657: 'scope',
 658: 'soap',
 659: 'events',
 660: 'platforms',
 661: 'get',
 662: 'supplier',
 663: 'type',
 664: 'bug',
 665: 'rewards',
 666: 'methodology',
 667: 'define',
 668: 'apps',
 669: 'designer',
 670: 'scheduling',
 671: 'non',
 672: 'quick',
 673: 'approach',
 674: 'being',
 675: 'availability',
 676: 'log',
 677: 'frameworks',
 678: 'goals',
 679: 'credit',
 680: 'career',
 681: 'scrum',
 682: 'prepared',
 683: 'entire',
 684: 'class',
 685: 'vendors',
 686: 'telecom',
 687: 'orders',
 688: 'check',
 689: 'updating',
 690: 'gcp',
 691: 'x',
 692: 'inc',
 693: 'attended',
 694: 'outlook',
 695: 'partners',
 696: 'transfer',
 697: 'learn',
 698: 'running',
 699: 'generating',
 700: 'android',
 701: 'handle',
 702: 'timely',
 703: 'recruitment',
 704: 'profile',
 705: 'first',
 706: 'travel',
 707: 'ip',
 708: 'deployed',
 709: 'written',
 710: 'summary',
 711: 'event',
 712: 'alm',
 713: 'presentation',
 714: 'experienced',
 715: 'gas',
 716: 'our',
 717: 'kolkata',
 718: 'directory',
 719: 'mule',
 720: 'escalations',
 721: 'openstack',
 722: 'maintained',
 723: 'enhancements',
 724: 'star',
 725: 'meet',
 726: 'remote',
 727: 'apache',
 728: 'able',
 729: 'responsibility',
 730: 'compliance',
 731: 'according',
 732: 'transaction',
 733: 'analyzing',
 734: 'specifications',
 735: 'mvc',
 736: 'pre',
 737: 'generation',
 738: 'so',
 739: 'bugs',
 740: 'extensive',
 741: 'docker',
 742: 'big',
 743: 'etl',
 744: 'list',
 745: 'fi',
 746: 'sr',
 747: 'lan',
 748: 'esb',
 749: 'base',
 750: 'debugging',
 751: 'enhancement',
 752: 'sessions',
 753: 'world',
 754: 'take',
 755: 'object',
 756: 'wide',
 757: 'coordination',
 758: 'configured',
 759: 'groups',
 760: 'national',
 761: 'regular',
 762: 'organizational',
 763: 'sla',
 764: 'opportunities',
 765: 'auto',
 766: 'assurance',
 767: 'rest',
 768: 'invoice',
 769: 'developers',
 770: 'billing',
 771: 'open',
 772: 'task',
 773: 'flow',
 774: 'page',
 775: 'extensively',
 776: 'chef',
 777: 'no',
 778: 'chandigarh',
 779: 'around',
 780: 'suite',
 781: 'splunk',
 782: 'administrator',
 783: 'contribution',
 784: 'delivered',
 785: 'progress',
 786: 'positive',
 787: 'expert',
 788: 'higher',
 789: 'conducted',
 790: 'month',
 791: 'vb',
 792: 'position',
 793: 'stock',
 794: 'practices',
 795: 'line',
 796: 'offers',
 797: 'webdriver',
 798: 'proficient',
 799: 'research',
 800: 'dashboard',
 801: 'looking',
 802: 'h',
 803: 'routers',
 804: 'builds',
 805: 'reviews',
 806: 'learner',
 807: 'metrics',
 808: 'success',
 809: 'ecc',
 810: 'do',
 811: 'coimbatore',
 812: 'updates',
 813: 'digital',
 814: 'improve',
 815: 'internet',
 816: 'proficiency',
 817: 'department',
 818: 'engine',
 819: 'hana',
 820: 'conducting',
 821: 'share',
 822: 'proven',
 823: 'executing',
 824: 'countries',
 825: 'some',
 826: 'market',
 827: 'specific',
 828: 'domains',
 829: 'insurance',
 830: 'were',
 831: 'single',
 832: 'need',
 833: 'function',
 834: 'there',
 835: 'packages',
 836: 'appropriate',
 837: 'tables',
 838: '11',
 839: 'delivering',
 840: 'workshop',
 841: 'verification',
 842: 'switch',
 843: 'individual',
 844: '10g',
 845: 'automating',
 846: 'now',
 847: 'fixing',
 848: 'achievements',
 849: 'dr',
 850: 'keep',
 851: 'managers',
 852: 'upgrade',
 853: 'small',
 854: 'utilize',
 855: 'component',
 856: 'spring',
 857: 'tomcat',
 858: 'display',
 859: 'trained',
 860: 'satisfaction',
 861: 'feedback',
 862: 'centre',
 863: 'k',
 864: 'relationship',
 865: 'standards',
 866: 'every',
 867: 'protocol',
 868: 'location',
 869: 'update',
 870: 'schedule',
 871: 'achieve',
 872: 'weblogic',
 873: 'logging',
 874: 'what',
 875: 'gives',
 876: 'response',
 877: 'very',
 878: 'joining',
 879: 'stakeholders',
 880: 'plant',
 881: 'prepare',
 882: 'consulting',
 883: 'raised',
 884: 'tcp',
 885: 'local',
 886: 'router',
 887: 'policies',
 888: 'form',
 889: 'waas',
 890: 'opportunity',
 891: 'machine',
 892: 'hard',
 893: 'excellence',
 894: 'root',
 895: 'involves',
 896: 'operational',
 897: 'checks',
 898: 'connectivity',
 899: 'installing',
 900: 'seeking',
 901: 'sc',
 902: 'driven',
 903: 'identify',
 904: 'productivity',
 905: 'scenarios',
 906: 'functionalities',
 907: 'commerce',
 908: 'period',
 909: 'soft',
 910: 'motivated',
 911: 'dhcp',
 912: 'contact',
 913: 'phase',
 914: 'trading',
 915: 'console',
 916: 'approval',
 917: 'deployments',
 918: 'ansible',
 919: 'efforts',
 920: 'operation',
 921: 'closely',
 922: 'strategic',
 923: 'certifications',
 924: 'wan',
 925: 'external',
 926: 'bihar',
 927: 'attendance',
 928: 'audit',
 929: 'php',
 930: 'cause',
 931: 'workflows',
 932: 'interaction',
 933: 'objective',
 934: 'os',
 935: 'basics',
 936: 'ca',
 937: 'mail',
 938: 'hcl',
 939: 'full',
 940: 'jquery',
 941: 'due',
 942: 'powerpoint',
 943: 'functions',
 944: 'mis',
 945: 'they',
 946: 'tester',
 947: '15',
 948: 'independently',
 949: 'vlan',
 950: 'lab',
 951: 'large',
 952: 'tests',
 953: 'several',
 954: 'make',
 955: '11g',
 956: 'ssis',
 957: 'successful',
 958: 'side',
 959: 'certificate',
 960: 'soa',
 961: 'singh',
 962: 'connection',
 963: 'portfolio',
 964: 'student',
 965: 'flexible',
 966: 'objectives',
 967: 'organized',
 968: 'reduce',
 969: 'effort',
 970: 'house',
 971: 'party',
 972: 'firewall',
 973: 'assisting',
 974: 'find',
 975: 'ticket',
 976: 'j2ee',
 977: 'messages',
 978: 'diploma',
 979: 'specialist',
 980: 'utilization',
 981: 'above',
 982: 'desktop',
 983: 'presentations',
 984: 'assigned',
 985: 'switches',
 986: 'port',
 987: 'meeting',
 988: 'following',
 989: 'made',
 990: 'inter',
 991: 'workflow',
 992: 'clear',
 993: 'since',
 994: 'two',
 995: 'ant',
 996: 'distribution',
 997: 'noida',
 998: 'primary',
 999: 'u',
 1000: 'insights',
 ...}

In [54]:
vocab_size = len(tokenizer.index_word) +1
vocab_size

9728

In [56]:
X_padded = pad_sequences(X_tokenized , padding='post')
X_padded

array([[3331, 3332,   37, ...,    0,    0,    0],
       [3337, 3338,  427, ...,    0,    0,    0],
       [2743, 2744, 2745, ...,    0,    0,    0],
       ...,
       [1889, 1671,   26, ...,    0,    0,    0],
       [3327, 3328, 1958, ...,    0,    0,    0],
       [1728,  621,  166, ...,    0,    0,    0]], dtype=int32)

In [65]:
max_len_x = max(len(x) for x in X_padded)
max_len_x

3015

In [64]:
X_padded.shape[1]

3015

In [66]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense ,Bidirectional

In [71]:
model = Sequential([
    Embedding(input_dim=vocab_size ,output_dim=100 ,input_length=max_len_x),
    Bidirectional(LSTM(300 ,return_sequences=True)),
    Bidirectional(LSTM(200 ,return_sequences=True)),
    Bidirectional(LSTM(100 ,return_sequences=True)),
    Dense(num_of_classes ,activation='softmax')
])

model.compile(loss='categorical_crossentropy' ,optimizer='adam' ,metrics=['accuracy'])

2023-12-30 21:10:07.730584: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-12-30 21:10:07.732491: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-12-30 21:10:07.734435: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_1_grad/concat/split_1/split_dim' with dtype int32
	 [[{{node gradients/split_1_grad/concat/split_1/split_dim}}]]
2023-12-30 21:10:07.928673: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/ReverseV2_grad/ReverseV2/ReverseV2/axis' with dtype int32 and shape [1]
	 [[{{node gradients/ReverseV2_grad/ReverseV2/ReverseV2/axis}}]]
2023-12-30 21:10:08.016831: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-12-30 21:10:08.019662: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-12-30 21:10:08.021993: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_1_grad/concat/split_1/split_dim' with dtype int32
	 [[{{node gradients/split_1_grad/concat/split_1/split_dim}}]]
2023-12-30 21:10:08.375610: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-12-30 21:10:08.377639: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-12-30 21:10:08.379425: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_1_grad/concat/split_1/split_dim' with dtype int32
	 [[{{node gradients/split_1_grad/concat/split_1/split_dim}}]]
2023-12-30 21:10:08.536122: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/ReverseV2_grad/ReverseV2/ReverseV2/axis' with dtype int32 and shape [1]
	 [[{{node gradients/ReverseV2_grad/ReverseV2/ReverseV2/axis}}]]
2023-12-30 21:10:08.622393: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-12-30 21:10:08.626052: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-12-30 21:10:08.629335: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_1_grad/concat/split_1/split_dim' with dtype int32
	 [[{{node gradients/split_1_grad/concat/split_1/split_dim}}]]
2023-12-30 21:10:08.947689: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-12-30 21:10:08.949618: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-12-30 21:10:08.951160: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_1_grad/concat/split_1/split_dim' with dtype int32
	 [[{{node gradients/split_1_grad/concat/split_1/split_dim}}]]
2023-12-30 21:10:09.119242: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/ReverseV2_grad/ReverseV2/ReverseV2/axis' with dtype int32 and shape [1]
	 [[{{node gradients/ReverseV2_grad/ReverseV2/ReverseV2/axis}}]]
2023-12-30 21:10:09.191630: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_2_grad/concat/split_2/split_dim' with dtype int32
	 [[{{node gradients/split_2_grad/concat/split_2/split_dim}}]]
2023-12-30 21:10:09.194087: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_grad/concat/split/split_dim' with dtype int32
	 [[{{node gradients/split_grad/concat/split/split_dim}}]]
2023-12-30 21:10:09.195735: I tensorflow/core/common_runtime/executor.cc:1197] [/device:CPU:0] (DEBUG INFO) Executor start aborting (this does not indicate an error and you can ignore this message): INVALID_ARGUMENT: You must feed a value for placeholder tensor 'gradients/split_1_grad/concat/split_1/split_dim' with dtype int32
	 [[{{node gradients/split_1_grad/concat/split_1/split_dim}}]]

In [72]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding_1 (Embedding)     (None, 3015, 100)         972800

 bidirectional_3 (Bidirectio  (None, 3015, 600)        962400
 nal)

 bidirectional_4 (Bidirectio  (None, 3015, 400)        1281600
 nal)

 bidirectional_5 (Bidirectio  (None, 3015, 200)        400800
 nal)

 dense_1 (Dense)             (None, 3015, 11)          2211

=================================================================
Total params: 3,619,811
Trainable params: 3,619,811
Non-trainable params: 0
_________________________________________________________________

In [76]:
y_padded = [pad_sequences(seq, padding='post', dtype='object') for seq in df['Y_iob']]
y_padded

[array([[[1295, 1622, 'B-Skills']],

        [[993, 1154, 'B-Skills']],

        [[939, 957, 'B-College Name']],

        [[883, 905, 'B-College Name']],

        [[856, 861, 'B-Graduation Year']],

        [[771, 814, 'B-College Name']],

        [[727, 770, 'B-Designation']],

        [[407, 416, 'B-Companies worked at']],

        [[372, 405, 'B-Designation']],

        [[95, 146, 'B-Email Address']],

        [[60, 69, 'B-Location']],

        [[49, 58, 'B-Companies worked at']],

        [[13, 46, 'B-Designation']],

        [[0, 12, 'B-Name']]], dtype=object),
 array([[[1155, 1199, 'B-Email Address']],

        [[743, 1141, 'B-Skills']],

        [[729, 733, 'B-Graduation Year']],

        [[675, 703, 'B-College Name']],

        [[631, 673, 'B-Degree']],

        [[625, 630, 'B-Graduation Year']],

        [[614, 623, 'B-College Name']],

        [[606, 612, 'B-Degree']],

        [[104, 148, 'B-Email Address']],

        [[62, 68, 'B-Location']],

        [[0, 14, 'B-Name']]], dtype=object),
 array([[[3749, 3757, 'B-Skills']],

        [[3709, 3718, 'B-Skills']],

        [[3664, 3672, 'B-Skills']],

        [[3636, 3645, 'B-Skills']],

        [[3542, 3550, 'B-Skills']],

        [[3526, 3530, 'B-Skills']],

        [[3510, 3515, 'B-Skills']],

        [[3489, 3498, 'B-Skills']],

        [[3468, 3478, 'B-Skills']],

        [[3421, 3458, 'B-College Name']],

        [[3381, 3420, 'B-Degree']],

        [[1664, 1673, 'B-Location']],

        [[1645, 1660, 'B-Companies worked at']],

        [[1620, 1643, 'B-Designation']],

        [[783, 792, 'B-Location']],

        [[764, 779, 'B-Companies worked at']],

        [[739, 762, 'B-Designation']],

        [[65, 117, 'B-Email Address']],

        [[22, 31, 'B-Location']],

        [[0, 21, 'B-Name']]], dtype=object),
 array([[[8098, 8384, 'B-Skills']],

        [[8008, 8050, 'B-Skills']],

        [[7994, 7998, 'B-Graduation Year']],

        [[7955, 7992, 'B-College Name']],

        [[7904, 7953, 'B-College Name']],

        [[5016, 5025, 'B-Location']],

        [[2391, 2433, 'B-Email Address']],

        [[1522, 1531, 'B-Location']],

        [[1512, 1518, 'B-Companies worked at']],

        [[1472, 1510, 'B-Designation']],

        [[1433, 1442, 'B-Location']],

        [[105, 147, 'B-Email Address']],

        [[62, 71, 'B-Location']],

        [[54, 60, 'B-Companies worked at']],

        [[13, 51, 'B-Designation']],

        [[0, 12, 'B-Name']]], dtype=object),
 array([[[2010, 2013, 'B-Degree']],

        [[973, 1703, 'B-Skills']],

        [[943, 949, 'B-Location']],

        [[922, 939, 'B-College Name']],

        [[903, 920, 'B-Degree']],

        [[862, 879, 'B-College Name']],

        [[857, 860, 'B-Degree']],

        [[795, 803, 'B-Designation']],

        [[738, 746, 'B-Designation']],

        [[454, 462, 'B-Designation']],

        [[294, 300, 'B-Location']],

        [[264, 272, 'B-Designation']],

        [[85, 130, 'B-Email Address']],

        [[43, 49, 'B-Location']],

        [[24, 41, 'B-Companies worked at']],

        [[14, 22, 'B-Designation']],

        [[0, 13, 'B-Name']]], dtype=object),
 array([[[2826, 2879, 'B-Skills']],

        [[2768, 2810, 'B-Skills']],

        [[2513, 2517, 'B-Graduation Year']],

        [[2468, 2477, 'B-Location']],

        [[2429, 2464, 'B-College Name']],

        [[2384, 2428, 'B-Degree']],

        [[2378, 2382, 'B-Graduation Year']],

        [[2329, 2353, 'B-College Name']],

        [[2300, 2328, 'B-Degree']],

        [[1767, 1808, 'B-Email Address']],

        [[980, 984, 'B-Graduation Year']],

        [[967, 971, 'B-Graduation Year']],

        [[934, 943, 'B-Location']],

        [[922, 930, 'B-Companies worked at']],

        [[398, 402, 'B-Graduation Year']],

        [[367, 376, 'B-Location']],

        [[355, 363, 'B-Companies worked at']],

        [[333, 353, 'B-Designation']],

        [[56, 97, 'B-Email Address']],

        [[12, 32, 'B-Designation']],

        [[0, 11, 'B-Name']]], dtype=object),
 array([[[3490, 3523, 'B-Skills']],

        [[3475, 3480, 'B-Graduation Year']],

        [[3422, 3450, 'B-College Name']],

        [[3388, 3420, 'B-Degree']],

        [[3382, 3387, 'B-Graduation Year']],

        [[3313, 3339, 'B-College Name']],

        [[3290, 3311, 'B-Degree']],

        [[1893, 1898, 'B-Graduation Year']],

        [[1789, 1827, 'B-Email Address']],

        [[1742, 1749, 'B-Companies worked at']],

        [[1722, 1740, 'B-Designation']],

        [[1491, 1497, 'B-Companies worked at']],

        [[1463, 1489, 'B-Designation']],

        [[1289, 1296, 'B-Companies worked at']],

        [[1257, 1264, 'B-Companies worked at']],

        [[1223, 1230, 'B-Companies worked at']],

        [[1192, 1199, 'B-Companies worked at']],

        [[563, 589, 'B-Designation']],

        [[510, 520, 'B-Years of Experience']],

        [[108, 146, 'B-Email Address']],

        [[60, 74, 'B-Location']],

        [[38, 58, 'B-Companies worked at']],

        [[38, 44, 'B-Companies worked at']],

        [[9, 35, 'B-Designation']],

        [[0, 8, 'B-Name']]], dtype=object),
 array([[[1970, 2083, 'B-Skills']],

        [[1675, 1926, 'B-Skills']],

        [[1632, 1639, 'B-Location']],

        [[1589, 1628, 'B-College Name']],

        [[1439, 1488, 'B-Degree']],

        [[730, 740, 'B-Designation']],

        [[476, 486, 'B-Companies worked at']],

        [[466, 476, 'B-Designation']],

        [[114, 124, 'B-Years of Experience']],

        [[25, 32, 'B-Location']],

        [[14, 24, 'B-Designation']],

        [[0, 13, 'B-Name']]], dtype=object),
 array([[[1710, 1721, 'B-Skills']],

        [[1692, 1707, 'B-Skills']],

        [[1404, 1433, 'B-Degree']],

        [[1250, 1279, 'B-College Name']],

        [[1244, 1248, 'B-Graduation Year']],

        [[1184, 1188, 'B-Graduation Year']],

        [[1134, 1161, 'B-College Name']],

        [[1122, 1132, 'B-Degree']],

        [[1116, 1120, 'B-Graduation Year']],

        [[1073, 1093, 'B-College Name']],

        [[1051, 1072, 'B-Degree']],

        [[1045, 1050, 'B-Graduation Year']],

        [[993, 1022, 'B-College Name']],

        [[955, 991, 'B-Degree']]], dtype=object),
 array([[[4197, 4960, 'B-Skills']],

        [[3913, 4045, 'B-Skills']],

        [[3899, 3903, 'B-Graduation Year']],

        [[3831, 3869, 'B-College Name']],

        [[3800, 3830, 'B-Degree']],

        [[3346, 3355, 'B-Designation']],

        [[2416, 2425, 'B-Designation']],

        [[2210, 2251, 'B-Email Address']],

        [[1467, 1476, 'B-Designation']],

        [[1270, 1279, 'B-Companies worked at']],

        [[1259, 1268, 'B-Designation']],

        [[324, 333, 'B-Companies worked at']],

        [[57, 98, 'B-Email Address']],

        [[24, 33, 'B-Companies worked at']],

        [[12, 21, 'B-Designation']],

        [[0, 11, 'B-Name']]], dtype=object),
 array([[[324, 562, 'B-Skills']],

        [[264, 293, 'B-College Name']],

        [[242, 262, 'B-College Name']],

        [[172, 181, 'B-Companies worked at']],

        [[149, 170, 'B-Designation']],

        [[89, 131, 'B-Location']],

        [[47, 54, 'B-Location']],

        [[36, 45, 'B-Companies worked at']],

        [[12, 33, 'B-Designation']],

        [[0, 11, 'B-Name']]], dtype=object),
 array([[[2394, 2479, 'B-Skills']],

        [[2254, 2361, 'B-Skills']],

        [[2240, 2244, 'B-Graduation Year']],

        [[2160, 2195, 'B-College Name']],

        [[826, 841, 'B-Companies worked at']],

        [[215, 219, 'B-Graduation Year']],

        [[191, 206, 'B-Companies worked at']],

        [[102, 144, 'B-Email Address']],

        [[59, 68, 'B-Location']],

        [[42, 57, 'B-Companies worked at']],

        [[12, 40, 'B-Designation']],

        [[0, 11, 'B-Name']]], dtype=object),
 array([[[1439, 1592, 'B-Skills']],

        [[1280, 1289, 'B-Location']],

        [[1258, 1277, 'B-College Name']],

        [[1248, 1256, 'B-Degree']],

        [[1220, 1229, 'B-Location']],

        [[1192, 1216, 'B-College Name']],

        [[1164, 1173, 'B-Location']],

        [[1131, 1160, 'B-College Name']],

        [[1118, 1129, 'B-Degree']],

        [[519, 525, 'B-Companies worked at']],

        [[464, 470, 'B-Companies worked at']],

        [[372, 381, 'B-Location']],

        [[362, 368, 'B-Companies worked at']],

        [[349, 360, 'B-Designation']],

        [[74, 113, 'B-Email Address']],

        [[31, 40, 'B-Location']],

        [[23, 29, 'B-Companies worked at']],

        [[9, 20, 'B-Designation']],

        [[0, 8, 'B-Name']]], dtype=object),
 array([[[1361, 1408, 'B-Email Address']],

        [[1219, 1348, 'B-Skills']],

        [[1176, 1204, 'B-College Name']],

        [[1170, 1174, 'B-Graduation Year']],

        [[1152, 1169, 'B-Degree']],

        [[1146, 1150, 'B-Graduation Year']],

        [[1138, 1142, 'B-Graduation Year']],

        [[1061, 1137, 'B-College Name']],

        [[1053, 1059, 'B-Degree']],

        [[419, 423, 'B-Graduation Year']],

        [[410, 417, 'B-Companies worked at']],

        [[394, 409, 'B-Designation']],

        [[81, 128, 'B-Email Address']],

        [[42, 51, 'B-Location']],

        [[0, 17, 'B-Name']]], dtype=object),
 array([[[868, 876, 'B-Skills']],

        [[813, 828, 'B-College Name']],

        [[762, 811, 'B-Degree']],

        [[715, 730, 'B-College Name']],

        [[708, 713, 'B-Degree']],

        [[651, 677, 'B-College Name']],

        [[632, 649, 'B-Degree']],

        [[457, 472, 'B-Companies worked at']],

        [[403, 416, 'B-Designation']],

        [[368, 372, 'B-Location']],

        [[349, 366, 'B-Designation']],

        [[52, 94, 'B-Email Address']],

        [[12, 16, 'B-Location']],

        [[0, 11, 'B-Name']]], dtype=object),
 array([[[1878, 1883, 'B-Skills']],

        [[1871, 1876, 'B-Skills']],

        [[1831, 1848, 'B-Skills']],

        [[1803, 1821, 'B-Skills']],

        [[1803, 1809, 'B-Companies worked at']],

        [[1735, 1740, 'B-Skills']],

        [[1709, 1714, 'B-Skills']],

        [[1680, 1685, 'B-Skills']],

        [[1646, 1650, 'B-Graduation Year']],

        [[1597, 1618, 'B-Degree']],

        [[1577, 1595, 'B-Degree']],

        [[1571, 1575, 'B-Graduation Year']],

        [[1502, 1543, 'B-College Name']],

        [[1486, 1500, 'B-Degree']],

        [[1088, 1098, 'B-Companies worked at']],

        [[1069, 1087, 'B-Designation']],

        [[332, 338, 'B-Companies worked at']],

        [[313, 330, 'B-Designation']],

        [[82, 122, 'B-Location']],

        [[39, 48, 'B-Location']],

        [[31, 37, 'B-Companies worked at']],

        [[11, 28, 'B-Designation']],

        [[0, 10, 'B-Name']]], dtype=object),
 array([[[11663, 12212, 'B-Skills']],

        [[11476, 11559, 'B-Skills']],

        [[11462, 11466, 'B-Graduation Year']],

        [[11433, 11440, 'B-Location']],

        [[11389, 11429, 'B-College Name']],

        [[11357, 11387, 'B-Degree']],

        [[11328, 11332, 'B-Graduation Year']],

        [[10147, 10154, 'B-Location']],

        [[7691, 7698, 'B-Location']],

        [[7632, 7636, 'B-Graduation Year']],

        [[6209, 6216, 'B-Location']],

        [[4386, 4393, 'B-Location']],

        [[4347, 4365, 'B-Designation']],

        [[2784, 2829, 'B-Email Address']],

        [[2053, 2071, 'B-Designation']],

        [[96, 141, 'B-Email Address']],

        [[54, 61, 'B-Location']],

        [[37, 53, 'B-Companies worked at']],

        [[16, 34, 'B-Designation']],

        [[0, 15, 'B-Name']]], dtype=object),
 array([[[4611, 4621, 'B-Skills']],

        [[4531, 4567, 'B-College Name']],

        [[4526, 4529, 'B-Degree']],

        [[4387, 4392, 'B-Companies worked at']],

        [[4368, 4385, 'B-Designation']],

        [[3848, 3857, 'B-Location']],

        [[3842, 3847, 'B-Companies worked at']],

        [[3768, 3773, 'B-Companies worked at']],

        [[3749, 3766, 'B-Designation']],

        [[3732, 3741, 'B-Location']],

        [[2726, 2783, 'B-Designation']],

        [[2203, 2212, 'B-Location']],

        [[2197, 2202, 'B-Companies worked at']],

        [[2138, 2195, 'B-Designation']],

        [[2035, 2077, 'B-Email Address']],

        [[133, 175, 'B-Email Address']],

        [[79, 88, 'B-Location']],

        [[73, 78, 'B-Companies worked at']],

        [[13, 70, 'B-Designation']],

        [[0, 12, 'B-Name']]], dtype=object),
 array([[[2444, 2469, 'B-Skills']],

        [[2415, 2440, 'B-Skills']],

        [[2403, 2412, 'B-Skills']],

        [[2355, 2399, 'B-Skills']],

        [[2293, 2305, 'B-Skills']],

        [[2172, 2210, 'B-Skills']],

        [[1338, 1341, 'B-Skills']],

        [[1119, 1122, 'B-Skills']],

        [[851, 860, 'B-Skills']],

        [[828, 831, 'B-Skills']],

        [[796, 807, 'B-Skills']],

        [[789, 795, 'B-Skills']],

        [[762, 768, 'B-Skills']],

        [[735, 741, 'B-Skills']],

        [[721, 725, 'B-Graduation Year']],

        [[714, 719, 'B-Location']],

        [[707, 712, 'B-Location']],

        [[677, 719, 'B-College Name']],

        [[665, 669, 'B-Graduation Year']],

        [[658, 663, 'B-Location']],

        [[651, 656, 'B-Location']],

        [[621, 663, 'B-College Name']],

        [[609, 613, 'B-Graduation Year']],

        [[557, 608, 'B-College Name']],

        [[552, 555, 'B-Degree']],

        [[491, 545, 'B-College Name']],

        [[486, 489, 'B-Degree']],

        [[404, 446, 'B-Designation']],

        [[92, 136, 'B-Email Address']],

        [[64, 69, 'B-Location']],

        [[57, 62, 'B-Location']],

        [[14, 56, 'B-Designation']],

        [[0, 13, 'B-Name']]], dtype=object),
 array([[[5893, 6043, 'B-Skills']],

        [[5879, 5883, 'B-Graduation Year']],

        [[5838, 5859, 'B-College Name']],

        [[3730, 3740, 'B-Companies worked at']],

        [[3319, 3329, 'B-Companies worked at']],

        [[3237, 3247, 'B-Companies worked at']],

        [[3147, 3157, 'B-Companies worked at']],

        [[3099, 3109, 'B-Companies worked at']],

        [[2059, 2069, 'B-Companies worked at']],

        [[1977, 1987, 'B-Companies worked at']],

        [[1887, 1897, 'B-Companies worked at']],

        [[1837, 1847, 'B-Companies worked at']],

        [[1772, 1782, 'B-Companies worked at']],

        [[1753, 1771, 'B-Designation']],

        [[729, 739, 'B-Companies worked at']],

        [[90, 143, 'B-Location']],

        [[37, 46, 'B-Location']],

        [[0, 14, 'B-Name']]], dtype=object),
 array([[[1749, 1755, 'B-Companies worked at']],

        [[1696, 1702, 'B-Companies worked at']],

        [[1417, 1423, 'B-Companies worked at']],

        [[1356, 1793, 'B-Skills']],

        [[1209, 1215, 'B-Companies worked at']],

        [[1136, 1248, 'B-Skills']],

        [[928, 932, 'B-Graduation Year']],

        [[858, 889, 'B-College Name']],

        [[821, 856, 'B-Degree']],

        [[787, 791, 'B-Graduation Year']],

        [[744, 750, 'B-Companies worked at']],

        [[722, 742, 'B-Designation']],

        [[658, 664, 'B-Companies worked at']],

        [[640, 656, 'B-Designation']],

        [[574, 580, 'B-Companies worked at']],

        [[555, 573, 'B-Designation']],

        [[470, 493, 'B-Companies worked at']],

        [[444, 469, 'B-Designation']],

        [[308, 314, 'B-Companies worked at']],

        [[234, 240, 'B-Companies worked at']],

        [[175, 198, 'B-Companies worked at']],

        [[93, 137, 'B-Email Address']],

        [[39, 48, 'B-Location']],

        [[13, 38, 'B-Designation']],

        [[0, 12, 'B-Name']]], dtype=object),
 array([[[2275, 2281, 'B-Companies worked at']],

        [[2235, 2241, 'B-Companies worked at']],

        [[1603, 1609, 'B-Companies worked at']],

        [[667, 703, 'B-Skills']],

        [[638, 658, 'B-College Name']],

        [[612, 637, 'B-Degree']],

        [[591, 611, 'B-College Name']],

        [[587, 590, 'B-Degree']],

        [[568, 574, 'B-Companies worked at']],

        [[526, 536, 'B-Designation']],

        [[515, 524, 'B-Location']],

        [[507, 513, 'B-Companies worked at']],

        [[491, 503, 'B-Designation']],

        [[429, 438, 'B-Location']],

        [[352, 361, 'B-Location']],

        [[296, 305, 'B-Location']],

        [[270, 279, 'B-Location']],

        [[262, 268, 'B-Companies worked at']],

        [[246, 258, 'B-Designation']],

        [[238, 244, 'B-Companies worked at']],

        [[226, 236, 'B-Designation']],

        [[177, 207, 'B-Designation']],

        [[150, 155, 'B-Years of Experience']],

        [[54, 63, 'B-Location']],

        [[43, 52, 'B-Location']],

        [[35, 41, 'B-Companies worked at']],

        [[19, 31, 'B-Designation']],

        [[0, 18, 'B-Name']]], dtype=object),
 array([[[2246, 2573, 'B-Skills']],

        [[1435, 1480, 'B-Email Address']],

        [[875, 964, 'B-Skills']],

        [[861, 865, 'B-Graduation Year']],

        [[837, 856, 'B-College Name']],

        [[773, 830, 'B-Degree']],

        [[767, 771, 'B-Graduation Year']],

        [[743, 762, 'B-College Name']],

        [[714, 741, 'B-Degree']],

        [[271, 280, 'B-Location']],

        [[233, 252, 'B-Designation']],

        [[96, 141, 'B-Email Address']],

        [[53, 62, 'B-Location']],

        [[38, 52, 'B-Companies worked at']],

        [[16, 35, 'B-Designation']],

        [[0, 15, 'B-Name']]], dtype=object),
 array([[[4652, 4850, 'B-Skills']],

        [[4607, 4612, 'B-Graduation Year']],

        [[4543, 4576, 'B-College Name']],

        [[4499, 4541, 'B-Degree']],

        [[4493, 4498, 'B-Graduation Year']],

        [[4441, 4471, 'B-College Name']],

        [[4410, 4428, 'B-Companies worked at']],

        [[2654, 2672, 'B-Companies worked at']],

        [[2632, 2652, 'B-Designation']],

        [[1323, 1328, 'B-Graduation Year']],

        [[1260, 1278, 'B-Companies worked at']],

        [[1238, 1258, 'B-Designation']],

        [[603, 616, 'B-Companies worked at']],

        [[487, 505, 'B-Companies worked at']],

        [[465, 485, 'B-Designation']],

        [[97, 144, 'B-Email Address']],

        [[53, 67, 'B-Location']],

        [[39, 52, 'B-Companies worked at']],

        [[16, 36, 'B-Designation']],

        [[0, 15, 'B-Name']]], dtype=object),
 array([[[1894, 2173, 'B-Skills']],

        [[1726, 1851, 'B-Skills']],

        [[1711, 1716, 'B-Graduation Year']],

        [[1643, 1678, 'B-College Name']],

        [[1610, 1642, 'B-Degree']],

        [[1433, 1468, 'B-College Name']],

        [[1385, 1390, 'B-Graduation Year']],

        [[1359, 1363, 'B-Location']],

        [[1327, 1356, 'B-College Name']],

        [[1276, 1325, 'B-Degree']],

        [[269, 274, 'B-Graduation Year']],

        [[242, 246, 'B-Location']],

        [[204, 238, 'B-Companies worked at']],

        [[181, 202, 'B-Designation']],

        [[145, 149, 'B-Location']],

        [[33, 37, 'B-Location']],

        [[17, 31, 'B-Designation']],

        [[0, 16, 'B-Name']]], dtype=object),
 array([[[1520, 1524, 'B-Graduation Year']],

        [[1507, 1518, 'B-Degree']],

        [[1496, 1500, 'B-Graduation Year']],

        [[1488, 1492, 'B-Graduation Year']],

        [[1440, 1463, 'B-College Name']],

        [[1415, 1439, 'B-Degree']],

        [[1409, 1413, 'B-Graduation Year']],

        [[1334, 1366, 'B-College Name']],

        [[1291, 1333, 'B-Degree']],

        [[917, 940, 'B-Skills']],

        [[413, 417, 'B-Graduation Year']],

        [[405, 409, 'B-Graduation Year']],

        [[356, 368, 'B-Skills']],

        [[313, 318, 'B-Companies worked at']],

        [[51, 101, 'B-Email Address']],

        [[12, 23, 'B-Location']],

        [[0, 11, 'B-Name']]], dtype=object),
 array([[[5510, 5514, 'B-Graduation Year']],

        [[5481, 5508, 'B-College Name']],

        [[5475, 5479, 'B-Graduation Year']],

        [[5426, 5440, 'B-College Name']],

        [[5419, 5425, 'B-Degree']],

        [[4077, 4085, 'B-Companies worked at']],

        [[1810, 1818, 'B-Companies worked at']],


In [77]:
import numpy as np
y_padded = np.array(y_padded)

/tmp/ipykernel_10964/2625285280.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  y_padded = np.array(y_padded)

In [74]:
model.fit(X_padded ,y_padded ,epochs=5)

2023-12-30 21:11:26.250061: W tensorflow/tsl/framework/cpu_allocator_impl.cc:83] Allocation of 42885360 exceeds 10% of free system memory.

ValueError: Data cardinality is ambiguous:
  x sizes: 220
  y sizes: 3556
Make sure all arrays contain the same number of samples.